### POST request to create new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Rahul Yadav",
  "email": "test@example.com",
  "address": "Brookfield",
  "dateOfBirth": "1999-01-02",
  "registeredDate": "2025-12-20"
}

###