### GET request to get all patients
## GET http://localhost:4000/patients/c590a750-e91d-4aae-80ac-65118ed2e291

##direct call to patient-service but for that we need to open the port 4000 on docker run config
##GET http://localhost:4000/patients
## In local call through api-gateway
## GET http://localhost:4004/api/patients


## GET http://lb- .elb.localhost.localstack.cloud:4004/api/patients

GET http://localhost:4004/api/patients/de0b9cb8-672a-4f4c-a35b-ff0bca47a3ec
Authorization: Bearer {{token}}
###