### GET request to get all patients
## GET http://localhost:4000/patients/c590a750-e91d-4aae-80ac-65118ed2e291

##direct call to patient-service but for that we need to open the port 4000 on docker run config
##GET http://localhost:4000/patients


GET http://localhost:4004/api/patients

###