### Updates an existing patient entity
PUT http://localhost:4000/patients/de0b9cb8-672a-4f4c-a35b-ff0bca47a3ec
Content-Type: application/json

{
  "address": "sitamarhi",
  "dateOfBirth": "2005-07-07",
  "email": "chotu@example.com",
  "name": "chotu"
}

###